# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5b8e6042b2e8693764894bd85707760c"
name = "chat-app-extension"
handle = "chat-app-extension"
application_url = "https://kathy-accommodate-gt-headers.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kathy-accommodate-gt-headers.trycloudflare.com/auth/callback",
  "https://kathy-accommodate-gt-headers.trycloudflare.com/auth/shopify/callback",
  "https://kathy-accommodate-gt-headers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
